### PR TITLE
More work on threat model

### PR DESCRIPTION
**Pull request by nikomatsakis**
Finished write-up, added some tests

### CODE REVIEW

**Comment by nikomatsakis** [comment]
I don't know why we are getting these errors. My hunch is that we are running with a different toolchain than I used locally. Annoying.

**Comment by nikomatsakis** [comment]
cc @oli-obk any advice here?

**Comment by oli-obk** [comment]
Yes, ui tests can change whenever you update your compiler. You could ignore stderr entirely and only rely on annotations in the test file if that is sufficient for your use case.

Otherwise, a rustup toolchain file is useful to ensure consistency across all contributors

**Comment by nikomatsakis** [comment]
@oli-obk I think annotations would suffice, how do I make that change?

**Comment by fpoli** [comment]
I think oli is referring to the `//~ ERROR` annotations that you already wrote. So, it should be enough to remove the `.stderr` files from this PR.

**Comment by oli-obk** [comment]
We'll need to switch ui_test to using `OutputConflictHandling::Ignore` in the Config struct

**Comment by nikomatsakis** [comment]
@oli-obk like that?

**Comment by oli-obk** [comment]
Yes, this is how bevy does it, too.

If you still want it updated regularly, a cronjob could auto-open PRs if the output changes

**Comment by nikomatsakis** [comment]
Oh, that'd be useful, no idea how hard that'd be to set up tho

**Pull request merged**
