### PR TITLE
Add JMX APIs to Java prelude

### PR DESCRIPTION
**Pull request by rcoh**
Currently, there is not straightforward way of defining a `java.*` package outside of Duchess

### CODE REVIEW

**Comment by wleslie** [comment]
In general, how do we decide which Java APIs go into the Duchess prelude? So far we've got a rather arbitrary subset of the Java standard library. If we continued adding whichever APIs any user needs, would we eventually end up reflecting the entire Java standard library here?

**Comment by PatelProjects** [comment]
The `GarbageCollectorMXBean` part looks good

I'd like the `MemoryPoolMXBean` interface exposing at least `getType()`, `getUsage` and `getCollectionUsage`, instead of the `MemoryMXBean`

**Comment by nikomatsakis** [comment]
A thought (not for this PR) is to have duchess export java.lang and java.util (or some set of known packages) and then have ability for other crates to do other stuff. Then we can even have duchess-java-foo crates too for convenience.

**Comment by wleslie** [comment]
@rcoh Makes sense. Assuming that we provide a general way to reflect arbitrary `java.*` classes in the future, would we be OK doing a breaking change to remove the JMX stuff from the prelude?

**Comment by rcoh** [comment]
maybe we will feature gate them or move them to a separate crate. However, I'd imagine for many folks access to the JMX APIs is going to be a generally useful feature.

**Pull request merged**
